name: linting, testing, building

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v2

            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: install modules
              run: npm install

            - name: build production project
              run: npm run build
              continue-on-error: false

            - name: linting typescript
              run: npm run lint:ts
              continue-on-error: false

            - name: linting css
              run: npm run lint:scss
              continue-on-error: false

            - name: unit testing
              run: npm run test:unit
              continue-on-error: false

            - name: build storybook
              run: npm run build-storybook
              continue-on-error: false

            - name: prettier fix
              run: npm run prettier:fix
              continue-on-error: false

            - name: Push changes
              if: success()
              run: |
                  git config --local user.email "ex3l4nt@gmail.com"
                  git config --local user.name "ihopeyoucanfly"
                  git add .
                  git commit -m "Pipeline passed [skip ci]"
                  git push
